import { DateChallenge } from '../types/date';

export const INITIAL_CHALLENGES: DateChallenge[] = [
  {
    id: 'ch-1',
    number: 1,
    title: 'Cita a Ciegas: Tú la Comida, Yo la Actividad',
    description: 'Uno de los dos elige en secreto el menú o restaurante y el otro planifica la actividad sorpresa posterior.',
    category: 'comida',
    budgetEstimated: 45,
    hint: 'Misterio y trabajo en equipo',
    isRevealed: false,
    isAddedToDates: false,
  },
  {
    id: 'ch-2',
    number: 2,
    title: 'Picnic Nocturno Bajo las Estrellas',
    description: 'Lleven una cobija, linterna y snacks a un parque o azotea para buscar constelaciones y hablar de sus sueños.',
    category: 'aire_libre',
    budgetEstimated: 20,
    hint: 'Cielo estrellado y cobijas',
    isRevealed: false,
    isAddedToDates: false,
  },
  {
    id: 'ch-3',
    number: 3,
    title: 'Retrato Mutuo Sin Ver el Papel',
    description: 'Con lápiz y papel, dibújense el uno al otro mirándose a los ojos fijamente sin levantar el lápiz ni mirar la hoja. ¡Risas garantizadas!',
    category: 'casa',
    budgetEstimated: 10,
    hint: 'Arte abstracto y miradas cómplices',
    isRevealed: false,
    isAddedToDates: false,
  },
  {
    id: 'ch-4',
    number: 4,
    title: 'Tour de Postres de la Ciudad',
    description: 'Vayan a 3 cafeterías o pastelerías distintas y prueben únicamente un postre especial en cada una.',
    category: 'comida',
    budgetEstimated: 40,
    hint: 'Dulces momentos compartidos',
    isRevealed: false,
    isAddedToDates: false,
  },
  {
    id: 'ch-5',
    number: 5,
    title: 'Noche de Spa y Masajes en Casa',
    description: 'Preparen velas aromáticas, música zen, cremas y aceites para darse un masaje relajante por turnos.',
    category: 'relax',
    budgetEstimated: 25,
    hint: 'Desconexión total y caricias',
    isRevealed: false,
    isAddedToDates: false,
  },
  {
    id: 'ch-6',
    number: 6,
    title: 'Maratón de Cine con Fuerte de Almohadas',
    description: 'Construyan un fuerte de cobijas y almohadas en la sala como cuando eran niños y vean su saga de películas favorita.',
    category: 'cine',
    budgetEstimated: 15,
    hint: 'Palomitas y nostalgia acogedora',
    isRevealed: false,
    isAddedToDates: false,
  },
  {
    id: 'ch-7',
    number: 7,
    title: 'Aventura en Bici o Patines por Rutas Nuevas',
    description: 'Alquilen o lleven sus bicis y exploren una ciclovía o barrio nuevo con parada para tomar un jugo natural.',
    category: 'aventura',
    budgetEstimated: 20,
    hint: 'Brisa fresca y deporte en pareja',
    isRevealed: false,
    isAddedToDates: false,
  },
  {
    id: 'ch-8',
    number: 8,
    title: 'Paseo por Librería Antigua y Regalo Secreto',
    description: 'Vayan a una librería y elijan un libro que crean que describe al otro o que le enseñará algo hermoso, con una dedicatoria escrita.',
    category: 'cultura',
    budgetEstimated: 35,
    hint: 'Letras de amor y dedicatorias',
    isRevealed: false,
    isAddedToDates: false,
  },
  {
    id: 'ch-9',
    number: 9,
    title: 'Desayuno Sorpresa en la Cama con Flores',
    description: 'El primero en despertar prepara tostadas francesas, café caliente y le lleva flores a la cama al otro.',
    category: 'casa',
    budgetEstimated: 20,
    hint: 'Mañanas de mimos y sonrisas',
    isRevealed: false,
    isAddedToDates: false,
  },
  {
    id: 'ch-10',
    number: 10,
    title: 'Cena Temática de un País Desconocido',
    description: 'Elijan un país al azar en el mapa y preparen juntos una cena con receta tradicional de ese país escuchando su música folclórica.',
    category: 'comida',
    budgetEstimated: 35,
    hint: 'Viaje gastronómico sin salir de casa',
    isRevealed: false,
    isAddedToDates: false,
  },
  {
    id: 'ch-11',
    number: 11,
    title: 'Escapada Fotográfica por la Ciudad',
    description: 'Salgan con cámaras o celulares a buscar los rincones más coloridos y tomen una sesión de fotos romántica el uno al otro.',
    category: 'aire_libre',
    budgetEstimated: 10,
    hint: 'Fotos para el muro de recuerdos',
    isRevealed: false,
    isAddedToDates: false,
  },
  {
    id: 'ch-12',
    number: 12,
    title: 'Noche de Preguntas Profundas y Recuerdos',
    description: 'Escriban 10 preguntas que nunca se han hecho en papelitos y respondan con total sinceridad con una copa de vino.',
    category: 'casa',
    budgetEstimated: 25,
    hint: 'Conexión emocional profunda',
    isRevealed: false,
    isAddedToDates: false,
  },
  {
    id: 'ch-13',
    number: 13,
    title: 'Visita a un Museo o Galería de Noche',
    description: 'Asistan a una noche de museos o exposición de arte y debatan qué obra representa mejor su relación.',
    category: 'cultura',
    budgetEstimated: 30,
    hint: 'Inspiración y elegancia',
    isRevealed: false,
    isAddedToDates: false,
  },
  {
    id: 'ch-14',
    number: 14,
    title: 'Recrear su Primera Cita',
    description: 'Vístanse igual que ese día, vayan al mismo lugar o pidan la misma comida y recuerden los nervios de aquel primer encuentro.',
    category: 'comida',
    budgetEstimated: 50,
    hint: 'Donde empezó la magia',
    isRevealed: false,
    isAddedToDates: false,
  },
  {
    id: 'ch-15',
    number: 15,
    title: 'Búsqueda del Tesoro Casera',
    description: 'Uno esconde 3 notas de amor y regalitos dulces por toda la casa con pistas en rima para que el otro los encuentre.',
    category: 'casa',
    budgetEstimated: 15,
    hint: 'Pistas ingeniosas y sorpresas',
    isRevealed: false,
    isAddedToDates: false,
  },
];
